### ISSUE TITLE
Environment variables in docker-compose.yml are not expanded

### ISSUE THREAD

**Issue by hieki** [runfinch/finch#124]
**Describe the bug**
Environment variables in `docker-compose.yml` are not expanded

**Steps to reproduce**
I have prepared the following `docker-compose.yml` Everything is based on https://github.com/containerd/nerdctl/blob/main/examples/compose-wordpress/docker-compose.yaml except for one line.

```yml
version: '3.7'
services:
  wordpress:
    image: wordpress:5.7
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ${HOME}/hello.txt:/root/hello.txt
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```

I have created a file to mount the volume.

```
echo $HOME
/Users/hieki

echo hello > ~/hello.txt
cat ~/hello.txt
hello
```

I ran the `finch compose up` command. It failed.

```
WARN[0000] Ignoring: volume: Bind: [CreateHostPath]
INFO[0000] Ensuring image wordpress:5.7
INFO[0000] Ensuring image mariadb:10.5
INFO[0000] Creating container myapp_wordpress_1
INFO[0000] Re-creating container myapp_db_1
FATA[0000] error while creating container myapp_wordpress_1: exit status 1
FATA[0000] exit status 1
```

I modify `docker-compose.yml` and rewrite the files to mount to absolute paths. It works fine.

```yml
version: '3.7'
services:
  wordpress:
    image: wordpress:5.7
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - /Users/hieki/hello.txt:/root/hello.txt
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:

```

```
finch compose up
WARN[0000] Ignoring: volume: Bind: [CreateHostPath]
INFO[0000] Ensuring image wordpress:5.7
INFO[0000] Ensuring image mariadb:10.5
INFO[0000] Creating container myapp_wordpress_1
INFO[0000] Re-creating container myapp_db_1
INFO[0000] Attaching to logs
wordpress_1 |AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.4.1.22. Set the 'ServerName' directive globally to suppress this message
wordpress_1 |AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.4.1.22. Set the 'ServerName' directive globally to suppress this message
wordpress_1 |[Fri Dec 16 12:35:10.369453 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.21 configured -- resuming normal operations
wordpress_1 |[Fri Dec 16 12:35:10.369539 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
db_1        |2022-12-16 12:35:10+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.18+maria~ubu2004 started.
db_1        |2022-12-16 12:35:10+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1        |2022-12-16 12:35:10+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.18+maria~ubu2004 started.
db_1        |2022-12-16 12:35:10+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
db_1        |2022-12-16 12:35:10 0 [Note] mysqld (mysqld 10.5.18-MariaDB-1:10.5.18+maria~ubu2004) starting as process 1 ...
db_1        |2022-12-16 12:35:10 0 [Warning] Could not increase number of max_open_files to more than 1024 (request: 32184)
db_1        |2022-12-16 12:35:10 0 [Warning] Changed limits: max_open_files: 1024  max_connections: 151 (was 151)  table_cache: 421 (was 2000)
db_1        |2022-12-16 12:35:10 0 [Note] InnoDB: Uses event mutexes
db_1        |2022-12-16 12:35:10 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1        |2022-12-16 12:35:10 0 [Note] InnoDB: Number of pools: 1
db_1        |2022-12-16 12:35:10 0 [Note] InnoDB: Using ARMv8 crc32 + pmull instructions
db_1        |2022-12-16 12:35:10 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: Using Linux native AIO
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: Completed initialization of buffer pool
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=45391,45391
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: 128 rollback segments are active.
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: 10.5.18 started; log sequence number 45403; transaction id 20
db_1        |2022-12-16 12:35:11 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1        |2022-12-16 12:35:11 0 [Note] Server socket created on IP: '::'.
db_1        |2022-12-16 12:35:11 0 [Note] InnoDB: Buffer pool(s) load completed at 221216 12:35:11
db_1        |2022-12-16 12:35:11 0 [Note] Reading of all Master_info entries succeeded
db_1        |2022-12-16 12:35:11 0 [Note] Added new Master_info '' to hash table
db_1        |2022-12-16 12:35:11 0 [Note] mysqld: ready for connections.
db_1        |Version: '10.5.18-MariaDB-1:10.5.18+maria~ubu2004'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```

**Expected behavior**
Environment variables in docker-compose.yml should be expanded.

**Workaround**
When using `docker compose run`, you can mount any file by using the `-v` option.
However, this is not available with `docker compose up`.
