### ISSUE TITLE
Support docker compose config content

### ISSUE THREAD

**Issue by lowang** [runfinch/finch#1406]
**What is the problem you're trying to solve?.**
I'm trying to define a file that would be mounted inside container:
```
services:
 clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_PASSWORD: password
    configs:
      - source: clickhouse_extra_config.xml
        target: /etc/clickhouse-server/config.d/clickhouse_extra_config.xml
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:

configs:
  clickhouse_extra_config.xml:
    content: |
      <clickhouse>
        <asynchronous_metrics_update_period_s>60</asynchronous_metrics_update_period_s>
      </clickhouse>
```
but `finch` fails to recognize that:
```
WARN[0000] Ignoring: config clickhouse_extra_config.xml: [Content]
FATA[0000] config "clickhouse_extra_config.xml": lacks file path
```

**Describe the feature you'd like**
Such config is perfectly valid in `docker` so I would expect finch to behave the same.
