### ISSUE TITLE
Finch does not support logging driver "none"

### ISSUE THREAD

**Issue by pruszel** [runfinch/finch#670]
**Describe the bug**
When I use the [logging](https://docs.docker.com/compose/compose-file/compose-file-v3/#logging) configuration for my compose service with the `driver` option set to `"none"`, then I get a fatal error and am unable to start my compose service.

**Steps to reproduce**
Given the following compose service definition inside `docker-compose.yaml`:

```
version: "3.7"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        logging:
            driver: "none"
        volumes:
            - esdata:/usr/share/elasticsearch/data:delegated
        ports:
            - 9201:9200
        networks:
            - dev

networks:
    dev:
volumes:
    esdata:
```

When I run `finch compose up elasticsearch` I get the following output:

```
INFO[0000] Ensuring image docker.elastic.co/elasticsearch/elasticsearch:6.5.1
INFO[0000] Creating container myapp-elasticsearch-1
FATA[0000] unknown logging driver "none": not found
FATA[0000] error while creating container myapp-elasticsearch-1: exit status 1
FATA[0000] exit status 1
```

I also tried to use the `logging` configuration with the `driver: "none"` option for a different service and got the same result.

**Expected behavior**
I expected the `elasticsearch` service to start successfully.

**Screenshots or logs**
N/A

**Additional context**
[finch-support-20231031104304.zip](https://github.com/runfinch/finch/files/13219805/finch-support-20231031104304.zip)
