### ISSUE TITLE
Finch does not support `tty` configuration

### ISSUE THREAD

**Issue by peterlopez** [runfinch/finch#671]
**Describe the bug**
When I use the [tty](https://docs.docker.com/compose/compose-file/05-services/#tty) configuration for my compose service, then I get a fatal error and am unable to start my compose service.

**Steps to reproduce**
Given the following compose service definition inside `docker-compose.yaml`:

```
version: "3.7"
services:
    node:
        build:
            context: .
            dockerfile: ./config/docker/node/Dockerfile
        tty: true
        env_file:
            - ./.env
        volumes:
            - ./:/src:delegated
            - node_modules:/src/node_modules:delegated

volumes:
    node_modules:
```

When I run `finch compose up node` I get the following output:

```
WARN[0000] Ignoring: service node: [EnvFile]
INFO[0000] Ensuring image myapp-node
INFO[0000] Creating container myapp-node-1
FATA[0000] currently StdinOpen(-i) and Tty(-t) should be same
FATA[0000] exit status 1
```

I also tried using the `tty` configuration for a different compose service and got the same result.

**Expected behavior**
I expected the `node` service to start successfully.

**Screenshots or logs**
N/A

**Additional context**
[finch-support-20231031104304.zip](https://github.com/runfinch/finch/files/13219981/finch-support-20231031104304.zip)
