### ISSUE TITLE
finch compose not supported --platform？？

### ISSUE THREAD

**Issue by haozi4263** [runfinch/finch#68]
finch  compose --platform=amd64 up
FATA[0000] unknown flag: --platform
FATA[0000] exit status 1

**Comment by AkihiroSuda** [comment]
The platform has to be specified in the `docker-compose.yaml`, not in the CLI flag

https://github.com/containerd/nerdctl/blob/330a9166052246e98235b088e911cfde9c8e343e/examples/compose-multi-platform/docker-compose.yaml#L4
```yaml
services:
  svc0:
    build: .
    platform: s390x
    ports:
      - 8080:80
  svc1:
    build: .
    platform: ppc64le
    ports:
      - 8081:80
```
