### ISSUE TITLE
Add features not to forget to execute `finch gen-docs generate -p cmd/finch/`

### ISSUE THREAD

**Issue by haytok** [runfinch/finch#942]
**What is the problem you're trying to solve?.**
A clear and concise description of the use case for this feature. Please provide an example, if possible.

When we create new commands or options, we need to create command references by executing `finch gen-docs generate -p cmd/finch/` on locally.

However, at the moment, the document, pull requests, and CI do not indicate that `finch gen-docs generate` needs to be run.

As a result, we often forgot to run this command and create reference.

**Describe the feature you'd like**
A clear and concise description of what you'd like to happen.

- [ ] Documentation
- [ ] Pull Request template
- [ ] CI

We need to add CI to detect whether `finch gen-docs generate -p cmd/finch/` is executed by way of 1 or 2 is needed.

1. Fail the CI if we forget to run `finch gen-docs generate`, so that when we check the failure, we can run `finch gen-docs generate` and push the updated references.

2. Run `finch gen-docs generate` periodically in CI, create a PR if there are updates to the references, and have it reviewed and merged.

**Additional context**

Note that this issue is created based on the comments from the following PR.

- https://github.com/runfinch/finch/pull/938#pullrequestreview-2045821584

**Comment by haytok** [comment]
Regarding option 1 for the CI, it would involve adding a CI step similar to the following.

```yaml
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      // Build Finch and Setup VM

      // Generate docs
      // finch gen-docs generate -p cmd/finch/

      - name: Check to generate docs
        run: |
          git add -N docs/cmd
          git diff --exit-code docs/cmd
```
